In [1]:
##Plant Leaf Desease detection

In [2]:
!pip install tensorflow matplotlib pandas numpy seaborn

In [3]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [4]:
training_set = tf.keras.utils.image_dataset_from_directory(
    "train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    data_format=None,
)

Found 70295 files belonging to 38 classes.


In [5]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    "valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    data_format=None,
)

Found 17572 files belonging to 38 classes.


In [6]:
for x,y in training_set:
    print(x, x.shape)
    print(y, y.shape)
    break

tf.Tensor(
[[[[ 94.75  95.75 113.75]
   [ 85.    86.   104.  ]
   [ 79.5   80.5   98.5 ]
   ...
   [136.25 141.25 161.25]
   [137.25 142.25 162.25]
   [142.25 147.25 167.25]]

  [[ 94.25  95.25 113.25]
   [ 85.75  86.75 104.75]
   [ 92.25  93.25 111.25]
   ...
   [135.5  140.5  160.5 ]
   [138.   143.   163.  ]
   [146.5  151.5  171.5 ]]

  [[100.25 101.25 119.25]
   [ 99.5  100.5  118.5 ]
   [105.   106.   124.  ]
   ...
   [136.25 141.25 161.25]
   [136.25 141.25 161.25]
   [140.75 145.75 165.75]]

  ...

  [[ 88.75  89.75 109.75]
   [ 85.    86.   106.  ]
   [ 80.75  81.75 101.75]
   ...
   [145.5  150.5  169.5 ]
   [154.75 159.75 178.75]
   [144.75 149.75 168.75]]

  [[ 96.75  97.75 117.75]
   [ 91.25  92.25 112.25]
   [ 99.   100.   120.  ]
   ...
   [141.75 146.75 165.75]
   [135.5  140.5  159.5 ]
   [131.5  136.5  155.5 ]]

  [[ 81.75  82.75 102.75]
   [ 84.    85.   105.  ]
   [ 76.25  77.25  97.25]
   ...
   [135.75 140.75 159.75]
   [133.5  138.5  157.5 ]
   [133.   138.   15

In [7]:
###BUILDING A MODEL

In [8]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
from tensorflow.keras.models import Sequential

In [9]:
model = Sequential()

In [10]:
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu", input_shape=[128, 128, 3]))
model.add(Conv2D(filters=32, kernel_size=3, activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=64, kernel_size=3, activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=128, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=128, kernel_size=3, activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=256, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=3, activation="relu"))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=512, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=512, kernel_size=3, activation="relu"))
model.add(MaxPooling2D(pool_size=2, strides=2))



C:\Users\ADMIN\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


NameError: name 'MaxPool2D' is not defined

In [ ]:
model.add(Flatten())

In [ ]:
model.add(Dropout(0.25))

In [ ]:
model.add(Dense(units=1500, activation="relu"))

In [ ]:
model.add(Dropout(0.4))

In [ ]:
##Otput Layer

In [ ]:
model.add(Dense(units=38, activation="softmax"))

In [ ]:
###compiling model

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam
              (learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

In [ ]:
###Model training

In [ ]:
training_history = model.fit(x=training_set,validation_data=validation_set, epochs=10)

In [ ]:
model.save("plant_prediction_2.keras")

In [ ]:
import json
with open("training_histo.json", "w") as f:
    json.dump(training_history.history, f)

In [ ]:
epochs = [i for i in range(1,11)]
plt.plot(epochs, training_history.history["accuracy"], color="red", label="Training accuracy")
plt.plot(epochs, training_history.history["val_accuracy"], color="blue", label="Validation accuracy")
plt.xlabel("No of Epochs")
plt.ylabel("Accuracy")
plt.title("Accuracy Visualization")
plt.legend()
plt.show()

In [ ]:
class_name = validation_set.class_names

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    "valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

In [ ]:
y_pred = model.predict(test_set)
print(y_pred, y_pred.shape)

In [ ]:
predicted_categories = tf.argmax(y_pred, axis=1)

In [1]:
print(predicted_categories)

NameError: name 'predicted_categories' is not defined